### ISSUE TITLE
Exchange Rate verursacht Error

### ISSUE THREAD

**Issue by stallingerl** [Doichain/electrum-doi#6]
y:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, MutableMapping
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/home/stallingerl/Documents/electrum-doi/electrum/gui/qt/main_window.py", line 919, in edit_changed
    rate = self.fx.exchange_rate() if self.fx else Decimal('NaN')
  File "/home/stallingerl/Documents/electrum-doi/electrum/exchange_rate.py", line 636, in exchange_rate
    return Decimal(rate)
TypeError: conversion from dict to Decimal is not supported
E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/home/stallingerl/Documents/electrum-doi/electrum/gui/qt/main_window.py", line 919, in edit_changed
    rate = self.fx.exchange_rate() if self.fx else Decimal('NaN')
  File "/home/stallingerl/Documents/electrum-doi/electrum/exchange_rate.py", line 636, in exchange_rate
    return Decimal(rate)
TypeError: conversion from dict to Decimal is not supported
E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/home/stallingerl/Documents/electrum-doi/electrum/gui/qt/main_window.py", line 871, in timer_actions
    self.update_wallet()
  File "/home/stallingerl/Documents/electrum-doi/electrum/gui/qt/main_window.py", line 1005, in update_wallet
    self.update_tabs()
  File "/home/stallingerl/Documents/electrum-doi/electrum/gui/qt/main_window.py", line 1012, in update_tabs
    self.history_model.refresh('update_tabs')
  File "/home/stallingerl/Documents/electrum-doi/electrum/util.py", line 412, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/stallingerl/Documents/electrum-doi/electrum/util.py", line 408, in do_profile
    o = func(*args, **kw_args)
  File "/home/stallingerl/Documents/electrum-doi/electrum/gui/qt/history_list.py", line 278, in refresh
    include_lightning=self.should_include_lightning_payments())
  File "/home/stallingerl/Documents/electrum-doi/electrum/util.py", line 412, in <lambda>
    return lambda *args, **kw_args: do_profile(args, kw_args)
  File "/home/stallingerl/Documents/electrum-doi/electrum/util.py", line 408, in do_profile
    o = func(*args, **kw_args)
  File "/home/stallingerl/Documents/electrum-doi/electrum/wallet.py", line 970, in get_full_history
    fiat_fields = self.get_tx_item_fiat(tx_hash=txid, amount_sat=value, fx=fx, tx_fee=item['fee_sat'])
  File "/home/stallingerl/Documents/electrum-doi/electrum/wallet.py", line 1136, in get_tx_item_fiat
    fiat_rate = self.price_at_timestamp(tx_hash, fx.timestamp_rate)
  File "/home/stallingerl/Documents/electrum-doi/electrum/wallet.py", line 2438, in price_at_timestamp
    return price_func(timestamp if timestamp else time.time())
  File "/home/stallingerl/Documents/electrum-doi/electrum/exchange_rate.py", line 690, in timestamp_rate
    return self.history_rate(date)
  File "/home/stallingerl/Documents/electrum-doi/electrum/exchange_rate.py", line 679, in history_rate
    return Decimal(rate)
TypeError: conversion from dict to Decimal is not supported

**Comment by stallingerl** [comment]
Time Format ist falsch. 

ValueError('dictionary update sequence element #0 has length 20; 2 is required')

 aktuell:      return dict([time_close, historicRate])
 original:     return dict([(datetime.utcfromtimestamp(h[0]/1000).strftime('%Y-%m-%d'), h[1])
                   for h in history['prices']])
